---
name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  build-and-test:
    name: Build and run tests

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            ## Access token to avoid triggering GitHub's rate limiting.
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Install Nix dependencies
        run: |
          nix develop .github/nix/ --command true

      - name: Try building SpacedOut
        run: |
          nix develop .github/nix/ --command dune build

      - name: Run tests
        run: |
          nix develop .github/nix/ --command dune test

  run-flake-checks:
    name: Run flake checks

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3.4.0

      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            ## Access token to avoid triggering GitHub's rate limiting.
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Run flake checks
        run: nix flake check .github/nix/ --print-build-logs
